export type MutationBehavior = 'automatic_in_scope' | 'automatic_out_of_scope' | 'workflow_only';
export type MutationInterception = 'first_party_api' | 'outside_interception';
export type MutationMethodClass =
  | `${'request' | 'requestWithStatus' | 'fetch' | 'xhr_open'}:${'POST' | 'PUT' | 'PATCH' | 'DELETE'}`
  | 'fetch:delegated_to_typed_request_options';

export interface DashboardMutationCatalogEntry {
  file: string;
  enclosingSymbol: string;
  methodClass: MutationMethodClass;
  pathCategory: string;
  behavior: MutationBehavior;
  interception: MutationInterception;
  fingerprint: string;
}

function entry(
  file: string,
  enclosingSymbol: string,
  methodClass: MutationMethodClass,
  pathCategory: string,
  behavior: MutationBehavior = 'workflow_only',
  interception: MutationInterception = 'first_party_api',
): DashboardMutationCatalogEntry {
  return Object.freeze({
    file,
    enclosingSymbol,
    methodClass,
    pathCategory,
    behavior,
    interception,
    fingerprint: [file, enclosingSymbol, methodClass, pathCategory].join(' :: '),
  });
}

const ENDPOINTS = 'dashboard/src/api/endpoints.ts';

export const DASHBOARD_MUTATION_CATALOG: readonly DashboardMutationCatalogEntry[] = Object.freeze([
  entry(
    'dashboard/src/api/client.ts',
    'requestWithStatus',
    'fetch:delegated_to_typed_request_options',
    'delegated_to_typed_request_options',
    'workflow_only',
    'outside_interception',
  ),
  entry(ENDPOINTS, 'logout', 'request:POST', '/auth/logout'),
  entry(ENDPOINTS, 'createPlacement', 'request:POST', '/api/placements'),
  entry(ENDPOINTS, 'createPlacementFromTour', 'request:POST', '/api/placements/from-tour'),
  entry(ENDPOINTS, 'transitionPlacement', 'request:POST', '/api/placements/:placementId/transition'),
  entry(ENDPOINTS, 'updatePlacement', 'request:PATCH', '/api/placements/:placementId'),
  entry(ENDPOINTS, 'patchPlacementNudge', 'request:PATCH', '/api/placements/:placementId/nudges/:nudgeId'),
  entry(ENDPOINTS, 'postNudgeSendNow', 'request:POST', '/api/placements/:placementId/nudges/:nudgeId/send-now'),
  entry(ENDPOINTS, 'provisionPlacementRelay', 'requestWithStatus:POST', '/api/placements/:placementId/relay'),
  entry(ENDPOINTS, 'setPlacementFollowUp', 'request:POST', '/api/placements/:placementId/deadline'),
  entry(ENDPOINTS, 'clearPlacementFollowUp', 'request:POST', '/api/placements/:placementId/deadline'),
  entry(ENDPOINTS, 'setTenantStatus', 'request:PATCH', '/api/contacts/:contactId/tenant-status'),
  entry(ENDPOINTS, 'setListingStatus', 'request:PATCH', '/api/units/:unitId/listing-status'),
  entry(ENDPOINTS, 'sendMessage', 'request:POST', '/api/conversations/:conversationId/messages'),
  entry(ENDPOINTS, 'presignMmsMedia', 'request:POST', '/api/media/presign'),
  entry(ENDPOINTS, 'confirmMmsMedia', 'request:POST', '/api/media/confirm'),
  entry(ENDPOINTS, 'sendEmail', 'request:POST', '/api/conversations/:conversationId/email'),
  entry(ENDPOINTS, 'presignEmailMedia', 'request:POST', '/api/email-media/presign'),
  entry(ENDPOINTS, 'confirmEmailMedia', 'request:POST', '/api/email-media/confirm'),
  entry(ENDPOINTS, 'markUnmatchedRead', 'request:POST', '/api/unmatched-email/:unmatchedId/read', 'automatic_in_scope'),
  entry(ENDPOINTS, 'linkUnmatched', 'request:POST', '/api/unmatched-email/:unmatchedId/link'),
  entry(ENDPOINTS, 'createContactFromUnmatched', 'request:POST', '/api/unmatched-email/:unmatchedId/create-contact'),
  entry(ENDPOINTS, 'spamUnmatched', 'request:POST', '/api/unmatched-email/:unmatchedId/spam'),
  entry(ENDPOINTS, 'releaseUnmatched', 'request:POST', '/api/unmatched-email/:unmatchedId/release'),
  entry(ENDPOINTS, 'dismissUnmatched', 'request:POST', '/api/unmatched-email/:unmatchedId/dismiss'),
  entry(ENDPOINTS, 'retryMessage', 'request:POST', '/api/conversations/:conversationId/messages/:messageId/retry'),
  entry(ENDPOINTS, 'addConversationMember', 'request:POST', '/api/conversations/:conversationId/members'),
  entry(ENDPOINTS, 'removeConversationMember', 'request:DELETE', '/api/conversations/:conversationId/members/:memberKey'),
  entry(ENDPOINTS, 'closeConversation', 'request:PATCH', '/api/conversations/:conversationId/close'),
  entry(ENDPOINTS, 'deferCloseNag', 'request:POST', '/api/conversations/:conversationId/close-nag/defer'),
  entry(ENDPOINTS, 'markConversationRead', 'request:POST', '/api/conversations/:conversationId/read', 'automatic_in_scope'),
  entry(ENDPOINTS, 'markConversationUnread', 'request:POST', '/api/conversations/:conversationId/unread'),
  entry(ENDPOINTS, 'createUnit', 'request:POST', '/api/units'),
  entry(ENDPOINTS, 'updateUnit', 'request:PATCH', '/api/units/:unitId'),
  entry(ENDPOINTS, 'deleteUnit', 'request:DELETE', '/api/units/:unitId'),
  entry(ENDPOINTS, 'restoreUnit', 'request:POST', '/api/units/:unitId/restore'),
  entry(ENDPOINTS, 'addUnitContact', 'request:POST', '/api/units/:unitId/contacts'),
  entry(ENDPOINTS, 'removeUnitContact', 'request:DELETE', '/api/units/:unitId/contacts/:contactId'),
  entry(ENDPOINTS, 'presignUnitPhotos', 'request:POST', '/api/units/:unitId/photos/presign'),
  entry(ENDPOINTS, 'uploadToPresignedPost', 'xhr_open:POST', 'external_presigned_storage', 'workflow_only', 'outside_interception'),
  entry(ENDPOINTS, 'uploadToPresignedPost', 'fetch:POST', 'external_presigned_storage', 'workflow_only', 'outside_interception'),
  entry(ENDPOINTS, 'confirmUnitPhotos', 'request:POST', '/api/units/:unitId/photos/confirm'),
  entry(ENDPOINTS, 'removeUnitPhoto', 'request:DELETE', '/api/units/:unitId/photos'),
  entry(ENDPOINTS, 'setUnitPhotoCover', 'request:PUT', '/api/units/:unitId/photos/cover'),
  entry(ENDPOINTS, 'updateContact', 'request:PATCH', '/api/contacts/:contactId'),
  entry(ENDPOINTS, 'acceptSuggestion', 'request:POST', '/api/contacts/:contactId/suggestions/:target/accept'),
  entry(ENDPOINTS, 'dismissSuggestion', 'request:POST', '/api/contacts/:contactId/suggestions/:target/dismiss'),
  entry(ENDPOINTS, 'createContact', 'request:POST', '/api/contacts'),
  entry(ENDPOINTS, 'addContactPhone', 'request:POST', '/api/contacts/:contactId/phones'),
  entry(ENDPOINTS, 'updateContactPhone', 'request:PATCH', '/api/contacts/:contactId/phones/:phoneKey'),
  entry(ENDPOINTS, 'removeContactPhone', 'request:DELETE', '/api/contacts/:contactId/phones/:phoneKey'),
  entry(ENDPOINTS, 'addContactEmail', 'request:POST', '/api/contacts/:contactId/emails'),
  entry(ENDPOINTS, 'updateContactEmail', 'request:PATCH', '/api/contacts/:contactId/emails/:emailKey'),
  entry(ENDPOINTS, 'removeContactEmail', 'request:DELETE', '/api/contacts/:contactId/emails/:emailKey'),
  entry(ENDPOINTS, 'setContactOptOut', 'request:POST', '/api/contacts/:contactId/opt-out'),
  entry(ENDPOINTS, 'setContactVoiceOptOut', 'request:POST', '/api/contacts/:contactId/voice-opt-out'),
  entry(ENDPOINTS, 'originateCall', 'request:POST', '/api/contacts/:contactId/call'),
  entry(ENDPOINTS, 'deleteContact', 'request:DELETE', '/api/contacts/:contactId'),
  entry(ENDPOINTS, 'ensureContactConversation', 'request:POST', '/api/contacts/:contactId/conversation'),
  entry(ENDPOINTS, 'ensureEmailConversation', 'request:POST', '/api/contacts/:contactId/email-conversation'),
  entry(ENDPOINTS, 'restoreContact', 'request:POST', '/api/contacts/:contactId/restore'),
  entry(ENDPOINTS, 'runExtraction', 'request:POST', '/api/contacts/:contactId/extraction-run'),
  entry(ENDPOINTS, 'devLogin', 'request:POST', '/auth/dev-login'),
  entry(ENDPOINTS, 'markInboxRead', 'request:POST', '/api/inbox/:contactId/read', 'automatic_in_scope'),
  entry(ENDPOINTS, 'markInboxRead', 'request:POST', '/api/inbox/read', 'automatic_in_scope'),
  entry(ENDPOINTS, 'markInboxUnread', 'request:POST', '/api/inbox/:contactId/unread'),
  entry(ENDPOINTS, 'markInboxUnread', 'request:POST', '/api/inbox/unread'),
  entry(ENDPOINTS, 'createBroadcast', 'request:POST', '/api/broadcasts', 'automatic_out_of_scope'),
  entry(ENDPOINTS, 'previewBroadcast', 'request:POST', '/api/broadcasts/:broadcastId/preview'),
  entry(ENDPOINTS, 'sendBroadcast', 'request:POST', '/api/broadcasts/:broadcastId/send'),
  entry(ENDPOINTS, 'updateBroadcastSeeds', 'request:PATCH', '/api/broadcasts/:broadcastId'),
  entry(ENDPOINTS, 'deleteBroadcast', 'request:DELETE', '/api/broadcasts/:broadcastId', 'automatic_out_of_scope'),
  entry(ENDPOINTS, 'inviteUser', 'request:POST', '/api/users'),
  entry(ENDPOINTS, 'setUserRole', 'request:PATCH', '/api/users/:userId/role'),
  entry(ENDPOINTS, 'removeUser', 'request:DELETE', '/api/users/:userId'),
  entry(ENDPOINTS, 'assignInboundVoiceLine', 'request:POST', '/api/users/:userId/inbound-voice-line'),
  entry(ENDPOINTS, 'clearInboundVoiceLine', 'request:DELETE', '/api/users/:userId/inbound-voice-line'),
  entry(ENDPOINTS, 'startCellVerify', 'request:POST', '/api/users/me/cell/verify-start'),
  entry(ENDPOINTS, 'confirmCellVerify', 'request:POST', '/api/users/me/cell/verify-confirm'),
  entry(ENDPOINTS, 'putSettings', 'request:PUT', '/api/settings'),
  entry(ENDPOINTS, 'subscribePush', 'request:POST', '/api/push/subscriptions'),
  entry(ENDPOINTS, 'unsubscribePush', 'request:DELETE', '/api/push/subscriptions'),
  entry(ENDPOINTS, 'sendPushTest', 'request:POST', '/api/push/test'),
  entry(ENDPOINTS, 'createTour', 'request:POST', '/api/tours'),
  entry(ENDPOINTS, 'addTourRosterMember', 'request:POST', '/api/tours/:tourId/roster/members'),
  entry(ENDPOINTS, 'removeTourRosterMember', 'request:DELETE', '/api/tours/:tourId/roster/members/:memberKey'),
  entry(ENDPOINTS, 'resetTourRoster', 'request:POST', '/api/tours/:tourId/roster/reset'),
  entry(ENDPOINTS, 'addTourRosterLiveMember', 'request:POST', '/api/tours/:tourId/roster/live-members'),
  entry(ENDPOINTS, 'removeTourRosterLiveMember', 'request:DELETE', '/api/tours/:tourId/roster/live-members/:memberKey'),
  entry(ENDPOINTS, 'previewTourRosterAdd', 'request:POST', '/api/tours/:tourId/roster/preview-add'),
  entry(ENDPOINTS, 'addPlacementRosterMember', 'request:POST', '/api/placements/:placementId/roster/members'),
  entry(ENDPOINTS, 'removePlacementRosterMember', 'request:DELETE', '/api/placements/:placementId/roster/members/:memberKey'),
  entry(ENDPOINTS, 'resetPlacementRoster', 'request:POST', '/api/placements/:placementId/roster/reset'),
  entry(ENDPOINTS, 'addPlacementRosterLiveMember', 'request:POST', '/api/placements/:placementId/roster/live-members'),
  entry(ENDPOINTS, 'removePlacementRosterLiveMember', 'request:DELETE', '/api/placements/:placementId/roster/live-members/:memberKey'),
  entry(ENDPOINTS, 'previewPlacementRosterAdd', 'request:POST', '/api/placements/:placementId/roster/preview-add'),
  entry(ENDPOINTS, 'cancelTourRosterAction', 'request:POST', '/api/tours/:tourId/roster/pending/:actionId/cancel'),
  entry(ENDPOINTS, 'applyTourRosterActionNow', 'request:POST', '/api/tours/:tourId/roster/pending/:actionId/apply-now'),
  entry(ENDPOINTS, 'dismissTourRosterAction', 'request:POST', '/api/tours/:tourId/roster/pending/:actionId/dismiss'),
  entry(ENDPOINTS, 'cancelPlacementRosterAction', 'request:POST', '/api/placements/:placementId/roster/pending/:actionId/cancel'),
  entry(ENDPOINTS, 'applyPlacementRosterActionNow', 'request:POST', '/api/placements/:placementId/roster/pending/:actionId/apply-now'),
  entry(ENDPOINTS, 'dismissPlacementRosterAction', 'request:POST', '/api/placements/:placementId/roster/pending/:actionId/dismiss'),
  entry(ENDPOINTS, 'patchTourReminder', 'request:PATCH', '/api/tours/:tourId/reminders/:reminderId'),
  entry(ENDPOINTS, 'postReminderSendNow', 'request:POST', '/api/tours/:tourId/reminders/:reminderId/send-now'),
  entry(ENDPOINTS, 'patchTour', 'request:PATCH', '/api/tours/:tourId'),
  entry(ENDPOINTS, 'createTourRelay', 'requestWithStatus:POST', '/api/tours/:tourId/relay'),
  entry('dashboard/src/routes/public/publicApi.ts', 'submitHousingFair', 'request:POST', '/public/housing-fair', 'workflow_only', 'outside_interception'),
]);
