// Regenerates docs/issues/INDEX.md from the per-issue files' frontmatter, and
// prints a summary. The INDEX is a derived, GITIGNORED convenience artifact — the
// source of truth is the individual docs/issues/<slug>.md files (one per issue), so
// concurrent agents adding issues on different branches never conflict on a shared list.
//
// Usage: npm run issues
// Agents can skip this entirely and just grep, e.g. `rg "^status: open" docs/issues/`.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('..', import.meta.url));
const issuesDir = path.join(repoRoot, 'docs', 'issues');

const REQUIRED = ['id', 'title', 'type', 'severity', 'status'];
const TYPES = ['bug', 'security', 'debt', 'improvement', 'decision'];
const SEVERITIES = ['high', 'med', 'low'];
const STATUSES = ['open', 'in-progress', 'deferred', 'resolved', 'wontfix'];
const OPEN_STATUSES = ['open', 'in-progress', 'deferred'];

const SEV_RANK = { high: 0, med: 1, low: 2 };
const STATUS_RANK = Object.fromEntries(STATUSES.map((s, i) => [s, i]));

// Minimal frontmatter parser: the block between the first two `---` lines, scalar
// `key: value` pairs only. No YAML dependency (and none wanted).
function parseFrontmatter(text) {
  if (!text.startsWith('---')) return null;
  const end = text.indexOf('\n---', 3);
  if (end === -1) return null;
  const block = text.slice(3, end).trim();
  const fields = {};
  for (const line of block.split('\n')) {
    const m = line.match(/^([A-Za-z][\w-]*):\s?(.*)$/);
    if (m) fields[m[1]] = m[2].trim();
  }
  return fields;
}

const warnings = [];
const issues = [];

for (const name of readdirSync(issuesDir)) {
  if (!name.endsWith('.md')) continue;
  if (name.startsWith('_') || name === 'README.md' || name === 'INDEX.md') continue;
  const slug = name.slice(0, -3);
  const fm = parseFrontmatter(readFileSync(path.join(issuesDir, name), 'utf8'));
  if (!fm) { warnings.push(`${name}: no frontmatter block — skipped`); continue; }
  for (const k of REQUIRED) if (!fm[k]) warnings.push(`${name}: missing required field "${k}"`);
  if (fm.id && fm.id !== slug) warnings.push(`${name}: id "${fm.id}" != filename slug "${slug}"`);
  if (fm.type && !TYPES.includes(fm.type)) warnings.push(`${name}: unknown type "${fm.type}"`);
  if (fm.severity && !SEVERITIES.includes(fm.severity)) warnings.push(`${name}: unknown severity "${fm.severity}"`);
  if (fm.status && !STATUSES.includes(fm.status)) warnings.push(`${name}: unknown status "${fm.status}"`);
  issues.push({ slug, ...fm });
}

issues.sort((a, b) =>
  (STATUS_RANK[a.status] ?? 99) - (STATUS_RANK[b.status] ?? 99) ||
  (SEV_RANK[a.severity] ?? 99) - (SEV_RANK[b.severity] ?? 99) ||
  String(b.created || '').localeCompare(String(a.created || '')) ||
  a.slug.localeCompare(b.slug));

const open = issues.filter((i) => OPEN_STATUSES.includes(i.status));
const closed = issues.filter((i) => !OPEN_STATUSES.includes(i.status));

const row = (i) =>
  `| ${i.severity ?? '?'} | ${i.type ?? '?'} | ${i.status ?? '?'} | [${i.slug}](./${i.slug}.md) | ${(i.title ?? '').replace(/\|/g, '\\|')} | ${i.area ?? ''} |`;
const table = (rows) =>
  rows.length
    ? ['| sev | type | status | id | title | area |', '|---|---|---|---|---|---|', ...rows.map(row)].join('\n')
    : '_none_';

const lines = [
  '<!-- GENERATED by `npm run issues` from docs/issues/<slug>.md — DO NOT EDIT BY HAND. Gitignored. -->',
  '# Issues — index',
  '',
  `${open.length} open · ${closed.length} closed · ${issues.length} total. ` +
    'Source of truth = the per-issue files; this is a derived view. See [README.md](./README.md).',
  '',
  '## Open',
  '',
  table(open),
  '',
  '## Closed',
  '',
  table(closed),
  '',
];
writeFileSync(path.join(issuesDir, 'INDEX.md'), lines.join('\n'));

process.stdout.write(`[issues] ${open.length} open, ${closed.length} closed, ${issues.length} total → docs/issues/INDEX.md\n`);
const bySev = SEVERITIES.map((s) => `${open.filter((i) => i.severity === s).length} ${s}`).join(' · ');
if (open.length) process.stdout.write(`[issues] open by severity: ${bySev}\n`);
if (warnings.length) {
  process.stdout.write(`[issues] ${warnings.length} warning(s):\n`);
  for (const w of warnings) process.stdout.write(`  - ${w}\n`);
}
